package foxu.sea.fight;

/**
 * 玩家战力常量
 * 
 * @author Alan
 * 
 */
public interface FightScoreConst
{

	/** SOMETHING_ELSE=0 其他,ALLIANCE_SKILL_UP=1 升级联盟技能,
					ALLIANCE_DINATE_SHIP=2 联盟捐献船只,BATTLE_GROUP_SKILL_POINT=3 联盟据点升级技能,
					SHIP_UP_OR_STRENGTH=4 船只改装或强化,CANLE_SHIP_UP_STRENGTH=5 取消船只改装或强化,
					ONLINE_PUSH_ALL=6 上线结算建造,PLAYER_LV_UP=7 玩家升级,
					SCIENCE_SHIP_COMPLETE=8 科技或船只生产完成,EQUIP_ON=9 装备配件,EQUIP_OFF=10 卸下配件,
					EQUIP_LEVEL_UP=11 配件升级,EQUIP_QUALITY_UP=12 配件进阶,
					CHECK_POINT_BUFF=13 关卡buff,REPARI_SHIPS=14 修复船只,USE_OFFICER=15 使用军官,
					OFFICER_PROMOTE_RANK=16 军官提升军衔,OFFICER_LV_UP=17 军官升级,
					COMMAND_LEVEL_UP=18 统御升级,CLEAR_PLAYER_SKILLS=19 清除玩家技能,
					EMPIRE_RELIEF=20 帝国援军,PLAYER_SKILL_UP=21 玩家技能升级,SHIP_LV_UP=22 升级船只星石,
					CLEAR_SHIP_LV=23 清除船只星石,LOTTO_STATE=24 军需乐透获取船只,LUCKY_CIRCLE=25 幸运轮盘获取船只,
					LUCKY_CLASSIC=26 幸运乐透获取船只 ,FIGHT_LOSE=27 战斗损失 ,NEW_PLAYER_AWARD=28 新手送船
					NEW_ACTIVITY=29 新增活动推送战斗力变化,ARENA_AWARD=30 战斗奖励,LUCK_INTIMACY=31亲密度抽奖
					*/
	public static final int SOMETHING_ELSE=0,ALLIANCE_SKILL_UP=1,
					ALLIANCE_DINATE_SHIP=2,BATTLE_GROUP_SKILL_POINT=3,
					SHIP_UP_OR_STRENGTH=4,CANLE_SHIP_UP_STRENGTH=5,
					ONLINE_PUSH_ALL=6,PLAYER_LV_UP=7,
					SCIENCE_SHIP_COMPLETE=8,EQUIP_ON=9,EQUIP_OFF=10,
					EQUIP_LEVEL_UP=11,EQUIP_QUALITY_UP=12,
					CHECK_POINT_BUFF=13,REPARI_SHIPS=14,USE_OFFICER=15,
					OFFICER_PROMOTE_RANK=16,OFFICER_LV_UP=17,
					COMMAND_LEVEL_UP=18,CLEAR_PLAYER_SKILLS=19,
					EMPIRE_RELIEF=20,PLAYER_SKILL_UP=21,SHIP_LV_UP=22,
					CLEAR_SHIP_LV=23,LOTTO_STATE=24,LUCKY_CIRCLE=25,
					LUCKY_CLASSIC=26,FIGHT_LOSE=27,NEW_PLAYER_AWARD=28,
					NEW_ACTIVITY=29,FIGHT_AWARD=30,LUCK_INTIMACY=31;
}
